INSERT INTO person(first_name, last_name, city, street)
('first_name1', 'last_name1', 'city1', 'street1')
('first_name2', 'last_name2', 'city2', 'street2')
('first_name3', 'last_name3', 'city3', 'street3')
('first_name4', 'last_name4', 'city4', 'street4')