DROP TABLE TEAMS_IN_TOURNAMENT;
DROP TABLE PLAYERS_IN_TEAM;
DROP TABLE TOURNAMENTS;
DROP TABLE PLAYERS;
DROP TABLE HISTORY_OF_BETS;
DROP TABLE MATCHES;
DROP TABLE TEAMS;
DROP TABLE BETS;
DROP TABLE INPUT_AND_OUTPUT;
DROP TABLE CLIENTS;

CREATE TABLE CLIENTS (
    ID NUMBER,
    NAME VARCHAR2(32),
    BALANCE NUMBER NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    DATE_OF_REGISTRATION DATE NOT NULL,
    INPUT_METHOD VARCHAR2(32) NOT NULL,
    OUTPUT_METHOD VARCHAR2(32) NOT NULL,
    LOGIN VARCHAR2(32) NOT NULL,
    PASSWORD VARCHAR2(32) NOT NULL,
    CONSTRAINT CLIENTS_PK PRIMARY KEY (ID)
);

CREATE TABLE INPUT_AND_OUTPUT (   
    TYPE_OF_OPERATION VARCHAR2(32) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    OPERATION_DATE DATE NOT NULL,
    CLIENT_ID NUMBER NOT NULL,
    CONSTRAINT INPUT_AND_OUTPUT_CLIENTS_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID)
);

CREATE TABLE TEAMS (
    ID NUMBER,
    NAME VARCHAR2(32) NOT NULL,
    WORLD_RANKING VARCHAR2(32),
    CONSTRAINT TEAMS_PK PRIMARY KEY (ID)
);

CREATE TABLE PLAYERS (
    ID NUMBER,
    NAME VARCHAR2(32),
    NICKNAME VARCHAR2(32) NOT NULL,
    DATE_OF_BIRTH DATE,
    INDIVIDUAL_ACHIVEMENTS VARCHAR2(32),
    CONSTRAINT PLAYERS_PK PRIMARY KEY (ID)
);

CREATE TABLE TOURNAMENTS (
    ID NUMBER,
    NAME VARCHAR2(32) NOT NULL,
    DATE_OF_START DATE NOT NULL,
    CONDITIONS VARCHAR2(32) NOT NULL,
    FORMAT_OF_TOURNAMENT VARCHAR2(32),
    PRIZE_POOL VARCHAR2(32),
    WINNER_ID NUMBER NOT NULL,
    MVP NUMBER,
    CONSTRAINT TOURNAMENTS_PK PRIMARY KEY (ID)
);

CREATE TABLE PLAYERS_IN_TEAM (
    TEAM_ID NUMBER NOT NULL,
    PLAYER_ID NUMBER NOT NULL,
    CONSTRAINT PLAYERS_IN_TEAM_PK PRIMARY KEY (TEAM_ID, PLAYER_ID),
    CONSTRAINT PLAYERS_IN_TEAM_TEAMS_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID),
    CONSTRAINT PLAYERS_IN_TEAM_PLAYERS_FK FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS (ID)
);

CREATE TABLE TEAMS_IN_TOURNAMENT (
    TEAM_ID NUMBER NOT NULL,
    TOURNAMENT_ID NUMBER NOT NULL,
    CONSTRAINT TEAMS_IN_TOURNAMENT_PK PRIMARY KEY (TEAM_ID, TOURNAMENT_ID),
    CONSTRAINT TEAMS_IN_TOURNAMENT_TEAMS_FK FOREIGN KEY (TEAM_ID) REFERENCES TEAMS (ID),
    CONSTRAINT TEAMS_IN_TOURNAMENT_TOURNAMENTS_FK FOREIGN KEY (TOURNAMENT_ID) REFERENCES TOURNAMENTS (ID)
);

CREATE TABLE MATCHES (
    ID NUMBER,
    FIRST_TEAM_ID NUMBER NOT NULL,
    SECOND_TEAM_ID NUMBER NOT NULL,
    DATE_OF_MATCH DATE NOT NULL,
    TOURNAMENT_ID NUMBER NOT NULL,
    FIRST_TEAM_AMOUNT NUMBER NOT NULL,
    SECOND_TEAM_AMOUNT NUMBER NOT NULL,
    RELATION_OF_THE_AMOUNTS NUMBER NOT NULL,
    FIRST_TEAM_COEFFICIENT  NUMBER NOT NULL,
    SECOND_TEAM_COEFFICIENT NUMBER  NOT NULL,
    CONDITIONS VARCHAR2(32) NOT NULL,
    WINNER_ID NUMBER NOT NULL,
    SCORE VARCHAR2(32) NOT NULL,
    CONSTRAINT MATCHES_PK PRIMARY KEY (ID),
    CONSTRAINT MATCHES_TEAMS_FK1 FOREIGN KEY (FIRST_TEAM_ID) REFERENCES TEAMS (ID),
    CONSTRAINT MATCHES_TEAMS_FK2 FOREIGN KEY (SECOND_TEAM_ID) REFERENCES TEAMS (ID)
);

CREATE TABLE BETS (
    ID NUMBER,
    BETTED_AMOUNT NUMBER NOT NULL,
    COEFFICIENT NUMBER NOT NULL,
    RESULTS VARCHAR2(32) NOT NULL,
    CONSTRAINT BETS_PK PRIMARY KEY (ID)
);

CREATE TABLE HISTORY_OF_BETS (
    CLIENT_ID NUMBER NOT NULL,
    BET_ID NUMBER NOT NULL,
    MATCH_ID NUMBER NOT NULL,
    CONSTRAINT HISTORY_OF_BETS_PK PRIMARY KEY (CLIENT_ID, BET_ID, MATCH_ID),
    CONSTRAINT HISTORY_OF_BETS_CLIENTS_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID),
    CONSTRAINT HISTORY_OF_BETS_BETS_FK FOREIGN KEY (BET_ID) REFERENCES BETS (ID),
    CONSTRAINT HISTORY_OF_BETS_MATCHES_FK FOREIGN KEY (MATCH_ID) REFERENCES MATCHES (ID)
 );